---
version: '3.4'
services:
  DefaultTrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SET_PARAMS: DefaultTrailingProfitMethod
      RUN_ON_SET: set_opt_params DefaultTrailingProfitMethod 0 -25 0
      SETFILE: /opt/sets/EA31337-DefaultTrailingMethod.set
      TEST_REPORT_NAME: EA31337-DefaultTrailingProfitMethod
  DefaultTrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SET_PARAMS: DefaultTrailingStopMethod
      RUN_ON_SET: set_opt_params DefaultTrailingStopMethod 0 -25 0
      SETFILE: /opt/sets/EA31337-DefaultTrailingMethod.set
      TEST_REPORT_NAME: EA31337-DefaultTrailingStopMethod
