---
version: '3.4'
services:
  Account_Conditions_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SET_PARAMS: Account_Conditions_Active
      RUN_ON_SET: set_opt_params Account_Conditions_Active 0 1
      SETFILE: /opt/sets/EA31337-Account_Conditions_Active.set
      TEST_REPORT_NAME: EA31337-Account_Conditions_Active
  # Test equity above balance actions.
  Account_Condition_1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SET_PARAMS: Account_Condition_1
      RUN_ON_SET: set_opt_params Account_Condition_1 2 5
      SETFILE: /opt/sets/EA31337-Action_On_Condition_01.set
      TEST_REPORT_NAME: EA31337-Account_Condition_01
  Market_Condition_1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=40
      SET_PARAMS: Market_Condition_1
      RUN_ON_SET: set_opt_params Market_Condition_1 1 19
      SETFILE: /opt/sets/EA31337-Action_On_Condition_01.set
      TEST_REPORT_NAME: EA31337-Market_Condition_01
  Action_On_Condition_1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=40
      SET_PARAMS: Action_On_Condition_1
      RUN_ON_SET: set_opt_params Action_On_Condition_1 0 10
      SETFILE: /opt/sets/EA31337-Action_On_Condition_01.set
      TEST_REPORT_NAME: EA31337-Action_On_Condition_01
