---
name: Optimize Strategy AC

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-ac'
      - 'optimize-strategy-ac-*'

jobs:
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/AC/Timeframes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA AC_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "$git_email"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add . && git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
