---
name: Optimize Actions

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-actions'
      - 'optimize-actions-*'

jobs:
  Condition1:
    defaults:
      run:
        shell: bash
        working-directory: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run Account_Condition_1
      - run: docker-compose run Market_Condition_1
      - run: docker-compose run Action_On_Condition_1
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "$git_email"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add . && git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Active:
    defaults:
      run:
        shell: bash
        working-directory: Actions
    needs: Condition1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run Account_Conditions_Active
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "$git_email"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add . && git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
